mynews/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required as auth
from django.contrib import admin
from news.views import SignUpView,Login, UserProfileDetailView,UserProfileEditView
from news.views import LinkCreateView,LinkDetailView, LinkDeleteView,LinkUpdateView
from news.views import VoteFormView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('news.urls')),
    url(r'^accounts', include('registration.backends.hmac.urls')),
    url(r"^users/(?P<slug>\w+)/$", UserProfileDetailView.as_view(),
        name="profile"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name="logout"),
    url(r'^register',SignUpView.as_view(), name='register'),
    url(r"edit_profile/$", auth(UserProfileEditView.as_view()),
        name="edit_profile"),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^link/create/$',auth(LinkCreateView.as_view()), name="link_create"),
    url(r"^link/(?P<pk>\d+)$", LinkDetailView.as_view(),
        name="link_detail"),
    url(r"^link/update/(?P<pk>\d+)/$", auth(LinkUpdateView.as_view()),
        name="link_update"),
    url(r"^link/delete/(?P<pk>\d+)/$", auth(LinkDeleteView.as_view()),
        name="link_delete"),
    url(r'^vote/$', auth(VoteFormView.as_view()), name="vote"),
]

news/urls.py
from . import views
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from news.views import LinkListView

urlpatterns = [
    
    #url(r'^trial', LinkListView.as_view(), name='trial'),
    #url(r'^$', views.index, name='index'),
    url(r'^$', LinkListView.as_view(), name='home'),
    #url(r'^register',UserFormView.as_view(), name='register'),
    ]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse

class LinkVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(LinkVoteCountManager, self).get_queryset().annotate(votes=Count('vote')).order_by('-submitted_on')

class news(models.Model):
    title = models.CharField("Headline", max_length=100)
    submitter = models.ForeignKey(User)
    submitted_on = models.DateTimeField(auto_now_add=True)
    rank_score = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=250, blank=True)
    description = models.TextField(blank=True)

    with_votes = LinkVoteCountManager()
    objects = models.Manager()            # default manager

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("link_detail", kwargs={"pk": str(self.id)})


class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(news)

    def __unicode__(self):
        return "%s voted %s" % (self.voter.username, self.link.title)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    # Extra attributes
    bio = models.TextField(null=True)

    def __unicode__(self):
        return "%s's profile" % self.user

def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

from django.db.models.signals import post_save
post_save.connect(create_profile, sender=User)

news/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import news, Vote
import requests


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class SignInForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(SignInForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username','email','password']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ("user",)

class LinkForm(forms.ModelForm):
    error_message = {
        'url_exists': 'The url alredy exists'
    }
    class Meta:
        model = news
        exclude = ("submitter", "rank_score")
        fields = ('title','url')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = super(LinkForm, self).clean()
        print(cleaned_data)

    def clean_url(self):
        url = self.cleaned_data['url']
        request = requests.get(url)
        if request.status_code != 200:
            raise forms.ValidationError('The URL is invalid')
        if news.objects.filter(url=url).exists():
            raise forms.ValidationError('The URL alredy exists')
        return url

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        exclude = ("user",)

news/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import ListView,DetailView,CreateView, View
from .models import news, Vote, Profile,UserProfile
from django.contrib.auth import authenticate, login,get_user_model
from .forms import SignInForm, SignUpForm,UserProfileForm,LinkForm, VoteForm
from django.views.generic.edit import UpdateView, DeleteView,FormView
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpResponseNotFound, Http404,  HttpResponseRedirect
import json


def index(request):
    return render(request, 'news/home.html')

class LinkListView(ListView):
    model = news
    queryset = news.with_votes.all()
    paginate_by = 5
    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted
        return context

class LinkCreateView(CreateView):
    model = news
    form_class = LinkForm
    template_name = 'news/link_form.html'
    success_url = ('/')

    def form_valid(self, form):
        f = form.save(commit=False)
        f.submitter = self.request.user
        form.save()
        return super(LinkCreateView, self).form_valid(form)

class LinkDetailView(DetailView):
    model = news
    template_name = 'news/link_detail.html'


class LinkUpdateView(UpdateView):
    model = news
    form_class = LinkForm
    template_name = 'news/link_form.html'

class LinkDeleteView(DeleteView):
    model = news
    template_name = 'news/link_delete.html'
    success_url = ('/')



class SignUpView(CreateView):
    model = Profile
    form_class = SignUpForm
    template_name = 'registration.html'
    #success_url = 'home'

    def form_valid(self, form):
        form.save()
        #messages.info(request, "Thanks for registering. You are now logged in.")
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password1'],
                            )
        login(self.request, user)
        return redirect('home')
        #return super(SignUpView, self).form_valid(form)


class UserProfileDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "user_detail.html"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user

class UserProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "edit_profile.html"

    def get_object(self, queryset=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("profile", kwargs={"slug": self.request.user})


class Login(FormView, View):

    template_name = 'news/login.html'
    form_class = AuthenticationForm
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):

        if request.user.is_authenticated():
            return HttpResponseRedirect("/")
        else:
            return super(Login, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(Login, self).form_valid(form)

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(FormView):
    form_class = VoteForm
    success_url= ('/')

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(news, pk=form.data["link"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, link=link)
        has_voted = (len(prev_votes) > 0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, link=link)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)


    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors }
        return self.create_response(ret, False)

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

news/templates/news/link_delete.html
{% extends "home.html" %}

{% block content %}
    <form method="post" action="{% url 'link_delete' pk=object.pk %}">
	  {% csrf_token %}
	  <a href="{% url 'link_detail' pk=object.pk %}">Go back</a> 
	  <p><input type="submit" value="Confirm deletion" /></p>
	</form> 
{% endblock content %}

news/templates/news/link_detail.html
{% extends "home.html" %}


{% block content %}
<style>
  #id_honeypot {
    display: none;
  }
</style>

{% if object.submitter == user %}
  <a href="{% url 'link_update' pk=object.pk %}">Edit</a> | 
  <a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
{% endif %}
<h2><a href="{{ object.url }}">{{ object.title }}</a></h2>

<div class="desc">
  {{ object.description }}
</div>

{% endblock %}

news/templates/news/link_form.html
{% extends "home.html" %}

{% block content %}

<div class="col-md-8 Link-form">
<h1>Add New</h1>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>       
            {% endfor %}
        {% endif %}

        <div class="form-group">
            <label for="{{ field.name }}">{{ field.label}}</label>
        {{ field }}
        </div>
        
    {% endfor %}
    <input type="Submit" class="btn btn-light">
</form>
</div>
{% endblock content %}

news/templates/news/login.html
{% extends "home.html" %}

{% block content %}
<div class="col-md-8 Link-form">
<h1>Log in</h1>
<form  action="" method="POST">
    {% csrf_token %}

    {% if form.errors %}
        <div class="alert alert-danger">
            Check your username and your password and try again
        </div>        
    {% endif %}
    {% for field in form  %}
        {% if field.errors %}
        {% endif %}
        <div class="form-group">
        <label for="{{ field.name }}">{{ field.label}}</label>
        {{ field }}
        </div>
    {% endfor %}
    <input type="submit" class="btn btn-light">
</form>



</div>
{% endblock content %}

news/templates/news/news_list.html
{% extends "home.html" %}

{% block content %}
{% if is_paginated %}
<ol class="list-group" start="{{ page_obj.start_index }}">
{% else %}
<ol class="list-group">
{% endif %}
{% for link in object_list %}
<form method="post" action="{% url 'vote' %}" class="vote_form">
  <li class="list-group-item">
    {% csrf_token %}
    <input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    {% if not user.is_authenticated %}
    <button disabled title="Please login to vote">+</button>
    {% elif link.pk not in voted %}
    <button>+</button>
    {% else %}
    <button>-</button>
    {% endif %}
    <a href="{{ link.url }}">{{ link.title }}</a>
    <div class="Link-detail">
        <span>{{ link.votes }} points</span> |
        <span><a href="{% url 'link_detail' pk=link.pk %}"> Details</a></span> |
        <span>submited by {{ link.submitter }}</span> |
        <span>submited on {{ link.submitted_on }}</span>
        {% if link.submitter == user %}
        <span><a href="{% url 'link_update' pk=link.pk %}">| Edit</a> | </span>
        <span><a href="{% url 'link_delete' pk=link.pk %}">Delete</a></span>
        {% endif %}

    </div>

  </li>
</form>
{% endfor %}
</ol>
{% if is_paginated %}
<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"> &lsaquo; Back &nbsp;  </a>
    {% endif %}
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&nbsp; More &rsaquo;</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}